# Site settings
title:"OpenBlend"
email:"info@openblend.org"
# > this means to ignore newlines until "baseurl:"
description:
# the subpath of your site, e.g. /blog/
baseurl:
# the base hostname & protocol for your site
url:

twitter_username:
github_username:

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal